name: Sync Branches

on:
  push:
    branches:
      - frontend
      - backend

jobs:
  sync-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge changes into main
        run: |
          git fetch origin
          git checkout main
          git merge --no-edit origin/${{ github.ref_name }}
          git push origin main
